FROM python:3.6.6

EXPOSE 8000

VOLUME [ "/var/www/data" ]

COPY analytics /var/www

WORKDIR /var/www/analytics

RUN pip install -r requirements.txt \
 && apt-get update && apt-get install -y \
    gnupg \
    curl \
    make \
    g++ \
    git

CMD ["python", "server.py"]
