FROM alpine:3.8

EXPOSE 8000

VOLUME [ "/var/www/data" ]

COPY server config /var/www

WORKDIR /var/www/server

#RUN apt-get update && apt-get install -y \
#  gnupg \
#  curl \
#  make \
#  g++

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - &&
    apt-get update &&
    apt-get install -y nodejs &&
    npm install &&
    npm run build

CMD ["npm", "start"]
