from detectors.general_detector import GeneralDetector
from detectors.pattern_detector import PatternDetector
from detectors.peaks_detector import PeaksDetector
from detectors.step_detector import StepDetector
from detectors.jump_detector import Jumpdetector
