{
 "title": "Hastic Exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(up{job=\"hastic-exporter\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Hastic Exporter Alive",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"hastic-exporter\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Last Alive",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "lastAlive{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Metric Last Pull",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "timestamp{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Analytic Alive",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ready{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{packageVersion}}-{{commitHash}}"
    }
   ]
  },
  {
   "title": "Queue Length for server's waited tasks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tasksQueueLength{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{packageVersion}}-{{commitHash}}"
    }
   ]
  },
  {
   "title": "Node: awaited tasks from analytics",
   "type": "corpglory-hastic-graph-panel",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "awaitedTasksNumber{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{ packageVersion }}-{{ commitHash  }}"
    }
   ]
  },
  {
   "title": "Active Webhooks",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "activeWebhooks{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{packageVersion}}-{{commitHash}}"
    }
   ]
  },
  {
   "title": "Detections Count since restart",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "detectionsCount{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{packageVersion}}-{{commitHash}}"
    }
   ]
  },
  {
   "title": "Detections per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(detectionsCount{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}-{{packageVersion}}-{{commitHash}}"
    }
   ]
  }
 ]
}